<script setup lang="ts">
// Client-only Redoc embed. Renders the OpenAPI spec referenced by the
// `spec` prop (a file under public/, generated by scripts/build_specs.py)
// with the full Redoc UI: searchable operation list, expanded parameters,
// request/response schemas, examples and a spec download button.
//
// Redoc.init only exists in the standalone UMD bundle (`redoc.standalone.js`),
// so it is loaded as a self-hosted asset via ?url and injected once per page;
// the spec itself is fetched from the site's public/ directory.
import { onMounted, ref } from 'vue'
import { withBase } from 'vitepress'
import standaloneUrl from 'redoc/bundles/redoc.standalone.js?url'

const props = defineProps<{ spec: string }>()

const el = ref<HTMLElement | null>(null)
const failed = ref(false)
const loading = ref(true)

declare global {
  interface Window {
    Redoc?: { init: (spec: object, options: object, el: HTMLElement, cb?: () => void) => void }
  }
}

// Offset anchors and sticky elements below the VitePress navbar.
function navOffset(): number {
  const v = getComputedStyle(document.documentElement).getPropertyValue('--vp-nav-height')
  return parseInt(v, 10) || 56
}

function loadStandalone(): Promise<void> {
  return new Promise((resolve, reject) => {
    if (window.Redoc) return resolve()
    const s = document.createElement('script')
    s.src = standaloneUrl
    s.onload = () => resolve()
    s.onerror = () => reject(new Error(`failed to load ${standaloneUrl}`))
    document.head.appendChild(s)
  })
}

onMounted(async () => {
  try {
    const [res] = await Promise.all([fetch(withBase(props.spec)), loadStandalone()])
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`)
    const spec = await res.json()
    const Redoc = window.Redoc
    if (!Redoc || !el.value) throw new Error('Redoc standalone not ready')
    Redoc.init(spec, {
      scrollYOffset: navOffset,
      hideDownloadButton: false,
      pathInMiddlePanel: true,
      jsonSampleExpandLevel: 2,
      showObjectSchemaExamples: true,
      lazyRendering: true,
      theme: {
        colors: { primary: { main: '#0053b3' } },
        typography: { fontSize: '15px', lineHeight: '1.6em' },
      },
    }, el.value, () => {
      loading.value = false
    })
    // Safety net in case the init callback never fires.
    setTimeout(() => {
      if (loading.value && el.value && el.value.innerHTML.length > 1000) loading.value = false
    }, 3000)
  } catch (e) {
    console.error('failed to render API reference', e)
    loading.value = false
    failed.value = true
  }
})
</script>

<template>
  <ClientOnly>
    <div class="api-reference">
      <div v-if="loading" class="redoc-loading">Loading API reference…</div>
      <div ref="el" class="redoc-holder" />
      <div v-if="failed" class="redoc-error">
        <p>Failed to render the API reference from <code>{{ spec }}</code>.</p>
        <p>
          The spec is generated at build time — run <code>pnpm gen</code> in
          <code>docs/web-api/</code> for local development, or download the
          <a :href="withBase(spec)">raw spec</a> directly.
        </p>
      </div>
    </div>
  </ClientOnly>
</template>

<style scoped>
.api-reference {
  margin-top: 8px;
}
.redoc-holder {
  min-height: 60vh;
}
.redoc-loading {
  color: var(--vp-c-text-2);
  padding: 48px 0;
  text-align: center;
}
.redoc-error {
  padding: 24px;
  border: 1px solid var(--vp-c-divider);
  border-radius: 8px;
}
</style>
