<script setup lang="ts">
// Client-only Redoc embed, used on a `layout: page` markdown page so that
// VitePress' `.vp-doc` typography (heading margins, table styles, link
// colors...) cannot leak into the Redoc panel and break its layout.
//
// Redoc.init only exists in the standalone UMD bundle (`redoc.standalone.js`),
// loaded as a self-hosted asset via ?url and injected once per page; the spec
// is fetched from the site's public/ directory (generated by
// scripts/build_specs.py from docs/api/swagger.yaml + i18n/zh.yaml).
import { computed, onMounted, ref } from 'vue'
import { withBase } from 'vitepress'
import standaloneUrl from 'redoc/bundles/redoc.standalone.js?url'

const props = defineProps<{ spec: string }>()

const zh = computed(() => props.spec.includes('.zh.'))
const title = computed(() => (zh.value ? 'API 参考' : 'API Reference'))
const intro = computed(() =>
  zh.value
    ? '完整的 REST/WebSocket/SSE 接口面——23 个功能分组共 232 个操作，渲染自仓库的 OpenAPI 3.0 规范（docs/api/swagger.yaml）。使用面板内的搜索框可按路径、摘要或参数名查找操作。'
    : 'The complete REST/WebSocket/SSE surface — 232 operations across 23 functional groups, rendered from the repository\'s OpenAPI 3.0 spec (docs/api/swagger.yaml). Use the search box inside the panel to find operations by path, summary or parameter name.',
)
const loadingText = computed(() => (zh.value ? '正在加载 API 参考…' : 'Loading API reference…'))
const failedTitle = computed(() => (zh.value ? 'API 参考渲染失败' : 'Failed to render the API reference'))

const el = ref<HTMLElement | null>(null)
const failed = ref(false)
const loading = ref(true)

declare global {
  interface Window {
    Redoc?: { init: (spec: object, options: object, el: HTMLElement, cb?: () => void) => void }
  }
}

// Offset anchors and sticky elements below the VitePress navbar.
function navOffset(): number {
  const v = getComputedStyle(document.documentElement).getPropertyValue('--vp-nav-height')
  return parseInt(v, 10) || 56
}

function loadStandalone(): Promise<void> {
  return new Promise((resolve, reject) => {
    if (window.Redoc) return resolve()
    const s = document.createElement('script')
    s.src = standaloneUrl
    s.onload = () => resolve()
    s.onerror = () => reject(new Error(`failed to load ${standaloneUrl}`))
    document.head.appendChild(s)
  })
}

onMounted(async () => {
  try {
    const [res] = await Promise.all([fetch(withBase(props.spec)), loadStandalone()])
    if (!res.ok) throw new Error(`${res.status} ${res.statusText}`)
    const spec = await res.json()
    const Redoc = window.Redoc
    if (!Redoc || !el.value) throw new Error('Redoc standalone not ready')
    Redoc.init(spec, {
      scrollYOffset: navOffset,
      hideDownloadButton: true,
      pathInMiddlePanel: true,
      jsonSampleExpandLevel: 2,
      showObjectSchemaExamples: true,
      lazyRendering: true,
      theme: {
        colors: { primary: { main: '#0053b3' } },
        typography: { fontSize: '15px', lineHeight: '1.6em' },
      },
    }, el.value, () => {
      loading.value = false
    })
    // Safety net in case the init callback never fires.
    setTimeout(() => {
      if (loading.value && el.value && el.value.innerHTML.length > 1000) loading.value = false
    }, 3000)
  } catch (e) {
    console.error('failed to render API reference', e)
    loading.value = false
    failed.value = true
  }
})
</script>

<template>
  <ClientOnly>
    <div class="ref-page">
      <header class="ref-header">
        <h1>{{ title }}</h1>
        <p>{{ intro }}</p>
      </header>
      <div class="ref-card">
        <div v-if="loading" class="ref-loading">{{ loadingText }}</div>
        <div ref="el" class="ref-holder" />
        <div v-if="failed" class="ref-error">
          <p><strong>{{ failedTitle }}</strong> — <code>{{ spec }}</code></p>
          <p v-if="zh">规范在构建时生成——本地开发请在 docs/web-api/ 下运行 <code>pnpm gen</code>，或直接下载<a :href="withBase(spec)">原始规范</a>。</p>
          <p v-else>The spec is generated at build time — run <code>pnpm gen</code> in <code>docs/web-api/</code> for local development, or download the <a :href="withBase(spec)">raw spec</a> directly.</p>
        </div>
      </div>
    </div>
  </ClientOnly>
</template>

<style scoped>
.ref-page {
  max-width: 1440px;
  margin: 0 auto;
  padding: calc(var(--vp-nav-height, 56px) + 32px) 24px 64px;
}
.ref-header h1 {
  margin: 0 0 8px;
  font-size: 28px;
  font-weight: 600;
  line-height: 40px;
  letter-spacing: -0.02em;
  color: var(--vp-c-text-1);
}
.ref-header p {
  margin: 0 0 24px;
  font-size: 15px;
  line-height: 1.7;
  color: var(--vp-c-text-2);
}
/* The Redoc panel keeps its own light theme; present it as a deliberate
   card so it reads cleanly against both light and dark site themes.
   No overflow clipping here — it would break Redoc's sticky sidebar. */
.ref-card {
  background: #ffffff;
  border: 1px solid var(--vp-c-divider);
  border-radius: 12px;
}
.ref-holder {
  min-height: 60vh;
}
.ref-loading {
  padding: 96px 0;
  text-align: center;
  color: #6b7280;
}
.ref-error {
  padding: 24px;
  color: #374151;
}
</style>
